# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 15:49
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('gitstorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blobmetadata',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
