# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 18:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gitstorage', '0002_auto_20151224_1549'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blobmetadata',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='treepermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
