# Generated by Django 2.2.3 on 2019-07-22 14:27

from pathlib import Path

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


def blob_upload_to(instance, filename):
    """Do as Git, partition blob data by the first two characters of the id."""
    return Path(instance.id[:2]) / filename


class Migration(migrations.Migration):

    dependencies = [
        ("gitstorage", "0002_auto_20170527_1215"),
    ]

    operations = [
        migrations.AddField(
            model_name="blob",
            name="ctime",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blob",
            name="mtime",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="blob",
            name="data",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(
                    base_url="/data/", location="data"
                ),
                upload_to=blob_upload_to,
            ),
        ),
    ]
