# Generated by Django 3.1.1 on 2020-09-21 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gitstorage", "0003_auto_20190722_1427"),
    ]

    operations = [
        # This will not drop the table but is reversible
        migrations.AlterModelOptions(
            name="blob",
            options={"managed": False},
        ),
    ]
