# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitstorage', '0003_auto_20151225_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blobmetadata',
            options={
                'swappable': 'GIT_STORAGE_BLOB_METADATA_MODEL',
            },
        ),
        migrations.AddField(
            model_name='blobmetadata',
            name='size',
            field=models.PositiveIntegerField(null=True, verbose_name='Size'),
        ),
    ]
