# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 11:23
from __future__ import unicode_literals

from django.db import migrations

from gitstorage.storage import GitStorage


def fill_size(apps, schema_editor):
    BlobMetadata = apps.get_model('gitstorage', 'BlobMetadata')
    if BlobMetadata._meta.swapped:
        return

    db_alias = schema_editor.connection.alias

    for metadata in BlobMetadata.objects.using(db_alias).filter(size__isnull=True).iterator():
        # Reopen the storage at each iteration to collect its memory ASAP
        storage = GitStorage()
        blob = storage.repository[metadata.id]
        metadata.size = blob.size
        metadata.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gitstorage', '0004_auto_20151230_1123'),
    ]

    operations = [
        migrations.RunPython(fill_size, atomic=False)
    ]
