# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitstorage', '0005_auto_20151230_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blobmetadata',
            name='size',
            field=models.PositiveIntegerField(verbose_name='Size'),
        ),
    ]
